services:

  # CATEGORY SERVICES
  
  Backoffice.category.CategoryRepository:
    class: ../../../../Contexts/Backoffice/Category/infrastructure/CategoryWebApiClient
    arguments: []

  Backoffice.category.CategorySave:
    class: ../../../../Contexts/Backoffice/Category/application/save/CategorySave
    arguments: ['@Backoffice.category.CategoryRepository']

  Backoffice.category.CategorySearch:
    class: ../../../../Contexts/Backoffice/Category/application/search/CategorySearch
    arguments: ['@Backoffice.category.CategoryRepository']

  Backoffice.category.CategorySaveCommandHandler:
    class: ../../../../Contexts/Backoffice/Category/application/save/CategorySaveCommandHandler
    arguments: ['@Backoffice.category.CategorySave']
    tags:
      - { name: 'commandHandler' }

  Backoffice.category.CategorySaveController:
    class: ../../../../apps/Backoffice/controllers/CategorySaveController
    arguments: ['@Shared.CommandBus']

  # PRODUCT CLASS SERVICES

  Backoffice.productClass.ProductClassRepository:
    class: ../../../../Contexts/Backoffice/ProductClass/infrastructure/ProductClassWebApiClient
    arguments: []

  Backoffice.productClass.ProductClassSave:
    class: ../../../../Contexts/Backoffice/ProductClass/application/save/ProductClassSave
    arguments: ['@Backoffice.productClass.ProductClassRepository']

  Backoffice.productClass.ProductClassPaginate:
    class: ../../../../Contexts/Backoffice/ProductClass/application/paginate/ProductClassPaginate
    arguments: ['@Backoffice.productClass.ProductClassRepository']

  Backoffice.productClass.ProductClassSaveCommandHandler:
    class: ../../../../Contexts/Backoffice/ProductClass/application/save/ProductClassSaveCommandHandler
    arguments: ['@Backoffice.productClass.ProductClassSave']
    tags:
      - { name: 'commandHandler' }

  Backoffice.productClass.ProductClassSaveController:
    class: ../../../../apps/Backoffice/controllers/ProductClassSaveController
    arguments: ['@Shared.CommandBus']


  # PARTNER PARTNER SERVICE
  
  Backoffice.partner.PartnerRepository:
    class: ../../../../Contexts/Backoffice/Partner/infrastructure/PartnerWebApiClient
    arguments: []

  Backoffice.partner.PartnerSave:
    class: ../../../../Contexts/Backoffice/Partner/application/save/PartnerSave
    arguments: ['@Backoffice.partner.PartnerRepository']

  Backoffice.partner.PartnerSaveCommandHandler:
    class: ../../../../Contexts/Backoffice/Partner/application/save/PartnerSaveCommandHandler
    arguments: ['@Backoffice.partner.PartnerSave']
    tags:
      - { name: 'commandHandler' }

  Backoffice.partner.PartnerSaveController:
    class: ../../../../apps/Backoffice/controllers/PartnerSaveController
    arguments: ['@Shared.CommandBus'] 


# PRODUCT PRODUCT PRODUCT
  Backoffice.product.ProductRepository:
    class: ../../../../Contexts/Backoffice/Product/infrastructure/ProductWebApiClient
    arguments: []

  Backoffice.product.ProductSave:
    class: ../../../../Contexts/Backoffice/Product/application/save/ProductSave
    arguments: ['@Backoffice.product.ProductRepository']

  Backoffice.product.ProductSaveCommandHandler:
    class: ../../../../Contexts/Backoffice/Product/application/save/ProductSaveCommandHandler
    arguments: ['@Backoffice.product.ProductSave']
    tags:
      - { name: 'commandHandler' }

  Backoffice.product.ProductSaveController:
    class: ../../../../apps/Backoffice/controllers/ProductSaveController
    arguments: ['@Shared.CommandBus'] 


# STOCK-RECORD  STOCK-RECORD  STOCK-RECORD
  Backoffice.stockRecord.StockRecordRepository:
    class: ../../../../Contexts/Backoffice/StockRecord/infrastructure/StockRecordWebApiClient
    arguments: []

  Backoffice.stockRecord.StockRecordSave:
    class: ../../../../Contexts/Backoffice/StockRecord/application/save/StockRecordSave
    arguments: ['@Backoffice.stockRecord.StockRecordRepository']

  Backoffice.stockRecord.StockRecordSaveCommandHandler:
    class: ../../../../Contexts/Backoffice/StockRecord/application/save/StockRecordSaveCommandHandler
    arguments: ['@Backoffice.stockRecord.StockRecordSave']
    tags:
      - { name: 'commandHandler' }

  Backoffice.stockRecord.StockRecordSaveController:
    class: ../../../../apps/Backoffice/controllers/StockRecordSaveController
    arguments: ['@Shared.CommandBus'] 